__title__ = 'django-slugify-processor'
__package_name__ = 'django_slugify_processor'
__version__ = '0.8.1'
__description__ = 'pipeline for slugification edgecases in django'
__email__ = 'i@devel.tech'
__author__ = 'devel.tech'
__license__ = 'BSD'
__copyright__ = 'Copyright 2017 devel.tech'
